@ECHO OFF
SETLOCAL

SET BUILD_DIR=BuildRelease64
SET BUILD_TARGET_PATH=%~dp0..\%BUILD_DIR%

IF EXIST "%BUILD_TARGET_PATH%" RMDIR /Q /S "%BUILD_TARGET_PATH%"
MKDIR "%BUILD_TARGET_PATH%"

PUSHD "%BUILD_TARGET_PATH%"
cmake ../Projects -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 15 2017 Win64"
CD ..
cmake --build "%BUILD_DIR%" --config Debug
POPD

ECHO done
