name: Build

on: [push, pull_request]

jobs:    
  steamrt:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        steamrt:
          - 'registry.gitlab.steamos.cloud/steamrt/scout/sdk'
          # - 'registry.gitlab.steamos.cloud/steamrt/scout/sdk/i386'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones speed things up
       - uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.docker }}:latest
          options: -v ${{ github.workspace }}:/og
          run: |
            cmake -S /og/Projects -B /og/Build -DCMAKE_BUILD_TYPE=Release -DSLIM_TIMING=No -DDBUILD_SERVER=On |
            && cmake --build ./Build --verbose -j4