name: Build

on: [push, pull_request]

jobs:    
  steamrt:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        docker:
          - 'registry.gitlab.steamos.cloud/steamrt/scout/sdk'
          - 'registry.gitlab.steamos.cloud/steamrt/scout/sdk/i386'
      fail-fast: false

    container: ${{ matrix.docker }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones speed things up
      - name: cmake configure
        run: cmake -S ./Projects -B ./Build -DCMAKE_BUILD_TYPE=Release -DSLIM_TIMING=No -DDBUILD_SERVER=On
      - name: compile with cmake
        run: cmake --build ./Build --verbose -j4